In [5]:
import numpy as np
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [6]:
a[-1]

np.int64(4)

In [7]:
b=np.array([1,2,3,4,5,6,7,8,9])
b[0:9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
c=b.copy()
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
d=b.view()
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=a.reshape(4,3)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [4]:
c=np.array([13,14,15])
np.concatenate((a,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [16]:
b = a.reshape(4, 3)   # 2-D array
d = a.view()          # still 2-D


In [17]:
np.array_split(d, 2)


[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]

In [18]:
np.where(d==4)

(array([3]),)

In [19]:
np.where(d%2==0)

(array([ 1,  3,  5,  7,  9, 11]),)

In [20]:
c=np.array([3,4,2,10,5])
np.sort(c)

array([ 2,  3,  4,  5, 10])

In [22]:
c=np.array([[2,3,1,4],[1,5,2,4]])
np.sort(c)

array([[1, 2, 3, 4],
       [1, 2, 4, 5]])

In [23]:
c=np.array(["apple","banana","mango","orange"])
np.sort(c)

array(['apple', 'banana', 'mango', 'orange'], dtype='<U6')

In [24]:
np.random.randint(100)

80

In [25]:
np.random.rand(10)

array([0.89548548, 0.71424148, 0.08165876, 0.05301423, 0.20929648,
       0.39577296, 0.00255841, 0.93220707, 0.27056861, 0.46919709])

In [26]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
np.ones(2)

array([1., 1.])

In [28]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])